const players = {
  "Aaron Banks": {
    name: "Aaron Banks",
    pick: 0,
    position: "IOL",
    backgroundColor: "#a1ac6f",
  },
  "Aaron Robinson": {
    name: "Aaron Robinson",
    pick: 0,
    position: "CB",
    backgroundColor: "#c6f4ce",
  },
  "Aashari Crosswell": {
    name: "Aashari Crosswell",
    pick: 0,
    position: "S",
    backgroundColor: "#16ac28",
  },
  "Adetokunbo Ogundeji": {
    name: "Adetokunbo Ogundeji",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#8b288e",
  },
  "Adrian Ealy": {
    name: "Adrian Ealy",
    pick: 0,
    position: "OT",
    backgroundColor: "#663c15",
  },
  "Adrian Hardy": {
    name: "Adrian Hardy",
    pick: 0,
    position: "WR",
    backgroundColor: "#55720c",
  },
  "Alaric Jackson": {
    name: "Alaric Jackson",
    pick: 0,
    position: "OT",
    backgroundColor: "#50d0d5",
  },
  "Alex Leatherwood": {
    name: "Alex Leatherwood",
    pick: 0,
    position: "OT",
    backgroundColor: "#9e8ac2",
  },
  "Ali Fayad": {
    name: "Ali Fayad",
    pick: 0,
    position: "IDL",
    backgroundColor: "#954c7c",
  },
  "Alijah Vera-Tucker": {
    name: "Alijah Vera-Tucker",
    pick: 0,
    position: "IOL",
    backgroundColor: "#4e3ca4",
  },
  "Alim McNeill": {
    name: "Alim McNeill",
    pick: 0,
    position: "IDL",
    backgroundColor: "#75c56b",
  },
  "Amari Rodgers": {
    name: "Amari Rodgers",
    pick: 0,
    position: "WR",
    backgroundColor: "#628e1e",
  },
  "Ambry Thomas": {
    name: "Ambry Thomas",
    pick: 0,
    position: "CB",
    backgroundColor: "#7fcf9f",
  },
  "Amen Ogbongbemiga": {
    name: "Amen Ogbongbemiga",
    pick: 0,
    position: "LB",
    backgroundColor: "#48da43",
  },
  "Amon-Ra St. Brown": {
    name: "Amon-Ra St. Brown",
    pick: 0,
    position: "WR",
    backgroundColor: "#332c19",
  },
  "Andre Cisco": {
    name: "Andre Cisco",
    pick: 0,
    position: "S",
    backgroundColor: "#02afd6",
  },
  "Anthony Hines III": {
    name: "Anthony Hines III",
    pick: 0,
    position: "LB",
    backgroundColor: "#81ea83",
  },
  "Anthony Schwartz": {
    name: "Anthony Schwartz",
    pick: 0,
    position: "WR",
    backgroundColor: "#9dc354",
  },
  "Antjuan Simmons": {
    name: "Antjuan Simmons",
    pick: 0,
    position: "LB",
    backgroundColor: "#000ed7",
  },
  "Antonio Nunn": {
    name: "Antonio Nunn",
    pick: 0,
    position: "WR",
    backgroundColor: "#1db106",
  },
  "Antonio Phillips": {
    name: "Antonio Phillips",
    pick: 0,
    position: "CB",
    backgroundColor: "#e1ec81",
  },
  "Ar'Darius Washington": {
    name: "Ar'Darius Washington",
    pick: 0,
    position: "S",
    backgroundColor: "#610885",
  },
  "Asante Samuel Jr.": {
    name: "Asante Samuel Jr.",
    pick: 0,
    position: "CB",
    backgroundColor: "#2ef3f6",
  },
  "Asim Rose": {
    name: "Asim Rose",
    pick: 0,
    position: "RB",
    backgroundColor: "#fe0124",
  },
  "Aubrey Solomon": {
    name: "Aubrey Solomon",
    pick: 0,
    position: "IDL",
    backgroundColor: "#506ab0",
  },
  "Austin Faoliu": {
    name: "Austin Faoliu",
    pick: 0,
    position: "IDL",
    backgroundColor: "#4af965",
  },
  "Austin Watkins": {
    name: "Austin Watkins",
    pick: 0,
    position: "WR",
    backgroundColor: "#b4466f",
  },
  "Avery Williams": {
    name: "Avery Williams",
    pick: 0,
    position: "CB",
    backgroundColor: "#6f068d",
  },
  "Azeez Ojulari": {
    name: "Azeez Ojulari",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#3ba2f2",
  },
  "Baron Browning": {
    name: "Baron Browning",
    pick: 0,
    position: "LB",
    backgroundColor: "#e828cd",
  },
  "Ben Cleveland": {
    name: "Ben Cleveland",
    pick: 0,
    position: "IOL",
    backgroundColor: "#381615",
  },
  "Ben DeLuca": {
    name: "Ben DeLuca",
    pick: 0,
    position: "S",
    backgroundColor: "#1ad290",
  },
  "Ben Mason": {
    name: "Ben Mason",
    pick: 0,
    position: "RB",
    backgroundColor: "#d34944",
  },
  "Ben Skowronek": {
    name: "Ben Skowronek",
    pick: 0,
    position: "WR",
    backgroundColor: "#a2656b",
  },
  "Benjamin St-Juste": {
    name: "Benjamin St-Juste",
    pick: 0,
    position: "CB",
    backgroundColor: "#5d0b6a",
  },
  "Blake Proehl": {
    name: "Blake Proehl",
    pick: 0,
    position: "WR",
    backgroundColor: "#0a6879",
  },
  "Bobby Brown III": {
    name: "Bobby Brown III",
    pick: 0,
    position: "IDL",
    backgroundColor: "#286fe5",
  },
  "Brady Breeze": {
    name: "Brady Breeze",
    pick: 0,
    position: "S",
    backgroundColor: "#87f99b",
  },
  "Brady Christensen": {
    name: "Brady Christensen",
    pick: 0,
    position: "OT",
    backgroundColor: "#60ca2d",
  },
  "Brady Davis": {
    name: "Brady Davis",
    pick: 0,
    position: "QB",
    backgroundColor: "#ba3c3b",
  },
  "Brady White": {
    name: "Brady White",
    pick: 0,
    position: "QB",
    backgroundColor: "#51f058",
  },
  "Brandon Smith": {
    name: "Brandon Smith",
    pick: 0,
    position: "WR",
    backgroundColor: "#0577e7",
  },
  "Brandon Stephens": {
    name: "Brandon Stephens",
    pick: 0,
    position: "CB",
    backgroundColor: "#097148",
  },
  "Brenden Jaimes": {
    name: "Brenden Jaimes",
    pick: 0,
    position: "OT",
    backgroundColor: "#890a1f",
  },
  "Brennan Eagles": {
    name: "Brennan Eagles",
    pick: 0,
    position: "WR",
    backgroundColor: "#921e80",
  },
  "Brett Kitrell": {
    name: "Brett Kitrell",
    pick: 0,
    position: "IOL",
    backgroundColor: "#7fe0f4",
  },
  "Brevin Jordan": {
    name: "Brevin Jordan",
    pick: 0,
    position: "TE",
    backgroundColor: "#ed8db5",
  },
  "Bryan Mills": {
    name: "Bryan Mills",
    pick: 0,
    position: "CB",
    backgroundColor: "#88a56c",
  },
  "Bryce Hargrove": {
    name: "Bryce Hargrove",
    pick: 0,
    position: "IOL",
    backgroundColor: "#845ffc",
  },
  "Bryce Thompson": {
    name: "Bryce Thompson",
    pick: 0,
    position: "CB",
    backgroundColor: "#4dcbce",
  },
  "Buddy Johnson": {
    name: "Buddy Johnson",
    pick: 0,
    position: "LB",
    backgroundColor: "#b72eb3",
  },
  "CJ Marable": {
    name: "CJ Marable",
    pick: 0,
    position: "RB",
    backgroundColor: "#9afba9",
  },
  "Cade Johnson": {
    name: "Cade Johnson",
    pick: 0,
    position: "WR",
    backgroundColor: "#7e4b49",
  },
  "Caden Sterns": {
    name: "Caden Sterns",
    pick: 0,
    position: "S",
    backgroundColor: "#04471d",
  },
  "Caleb Farley": {
    name: "Caleb Farley",
    pick: 0,
    position: "CB",
    backgroundColor: "#5ac958",
  },
  "Caleb Huntley": {
    name: "Caleb Huntley",
    pick: 0,
    position: "RB",
    backgroundColor: "#b0e81a",
  },
  "Caleb Kelly": {
    name: "Caleb Kelly",
    pick: 0,
    position: "LB",
    backgroundColor: "#e6c17e",
  },
  "Calvin Ashley": {
    name: "Calvin Ashley",
    pick: 0,
    position: "OT",
    backgroundColor: "#f3cc26",
  },
  "Cameron McGrone": {
    name: "Cameron McGrone",
    pick: 0,
    position: "LB",
    backgroundColor: "#46a29b",
  },
  "Cameron Sample": {
    name: "Cameron Sample",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#5ea77f",
  },
  "Camryn Bynum": {
    name: "Camryn Bynum",
    pick: 0,
    position: "CB",
    backgroundColor: "#952445",
  },
  "Carlo Kemp": {
    name: "Carlo Kemp",
    pick: 0,
    position: "IDL",
    backgroundColor: "#02d845",
  },
  "Carlos Basham Jr.": {
    name: "Carlos Basham Jr.",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#f9166f",
  },
  "Carson Green": {
    name: "Carson Green",
    pick: 0,
    position: "OT",
    backgroundColor: "#95e837",
  },
  "Cary Angeline": {
    name: "Cary Angeline",
    pick: 0,
    position: "TE",
    backgroundColor: "#93539c",
  },
  "Charles Snowden": {
    name: "Charles Snowden",
    pick: 0,
    position: "LB",
    backgroundColor: "#81a118",
  },
  "Chatarius Atwell": {
    name: "Chatarius Atwell",
    pick: 0,
    position: "WR",
    backgroundColor: "#e5f35a",
  },
  "Chauncey Golston": {
    name: "Chauncey Golston",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#af7b9c",
  },
  "Chazz Surratt": {
    name: "Chazz Surratt",
    pick: 0,
    position: "LB",
    backgroundColor: "#2f3f51",
  },
  "Chris Evans": {
    name: "Chris Evans",
    pick: 0,
    position: "RB",
    backgroundColor: "#eaf2e5",
  },
  "Chris Rumph II": {
    name: "Chris Rumph II",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#1ecc8e",
  },
  "Chris Wilcox": {
    name: "Chris Wilcox",
    pick: 0,
    position: "CB",
    backgroundColor: "#62865a",
  },
  "Christian Barmore": {
    name: "Christian Barmore",
    pick: 0,
    position: "IDL",
    backgroundColor: "#f4791b",
  },
  "Christian Darrisaw": {
    name: "Christian Darrisaw",
    pick: 0,
    position: "OT",
    backgroundColor: "#2162f6",
  },
  "Christian Uphoff": {
    name: "Christian Uphoff",
    pick: 0,
    position: "S",
    backgroundColor: "#88c296",
  },
  "Chuba Hubbard": {
    name: "Chuba Hubbard",
    pick: 0,
    position: "RB",
    backgroundColor: "#c604b7",
  },
  "Cole Van Lanen": {
    name: "Cole Van Lanen",
    pick: 0,
    position: "OT",
    backgroundColor: "#31fb27",
  },
  "Conner Olson": {
    name: "Conner Olson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#277e31",
  },
  "Connor Wedington": {
    name: "Connor Wedington",
    pick: 0,
    position: "WR",
    backgroundColor: "#f7ad51",
  },
  "Cornell Powell": {
    name: "Cornell Powell",
    pick: 0,
    position: "WR",
    backgroundColor: "#f79f07",
  },
  "Creed Humphrey": {
    name: "Creed Humphrey",
    pick: 0,
    position: "IOL",
    backgroundColor: "#9404fd",
  },
  "D'Ante Smith": {
    name: "D'Ante Smith",
    pick: 0,
    position: "OT",
    backgroundColor: "#8f7f52",
  },
  "D'Wayne Eskridge": {
    name: "D'Wayne Eskridge",
    pick: 0,
    position: "WR",
    backgroundColor: "#69df3c",
  },
  "D'antne Demery": {
    name: "D'antne Demery",
    pick: 0,
    position: "IOL",
    backgroundColor: "#4e7b51",
  },
  "DJ Daniel": {
    name: "DJ Daniel",
    pick: 0,
    position: "CB",
    backgroundColor: "#25ea91",
  },
  "Daelin Hayes": {
    name: "Daelin Hayes",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#a62142",
  },
  "Damar Hamlin": {
    name: "Damar Hamlin",
    pick: 0,
    position: "S",
    backgroundColor: "#a6f40d",
  },
  "Damon Hazelton": {
    name: "Damon Hazelton",
    pick: 0,
    position: "WR",
    backgroundColor: "#200696",
  },
  "Damonte Coxie": {
    name: "Damonte Coxie",
    pick: 0,
    position: "WR",
    backgroundColor: "#925474",
  },
  "Dan Moore Jr.": {
    name: "Dan Moore Jr.",
    pick: 0,
    position: "OT",
    backgroundColor: "#8f3f18",
  },
  "Danny Godlevske": {
    name: "Danny Godlevske",
    pick: 0,
    position: "IOL",
    backgroundColor: "#66c5c8",
  },
  "Darius Stills": {
    name: "Darius Stills",
    pick: 0,
    position: "IDL",
    backgroundColor: "#bd88aa",
  },
  "Darren Hall": {
    name: "Darren Hall",
    pick: 0,
    position: "S",
    backgroundColor: "#a30ce3",
  },
  "Darrick Forrest": {
    name: "Darrick Forrest",
    pick: 0,
    position: "S",
    backgroundColor: "#360580",
  },
  "David Moore": {
    name: "David Moore",
    pick: 0,
    position: "IOL",
    backgroundColor: "#56b992",
  },
  "Davis Mills": {
    name: "Davis Mills",
    pick: 0,
    position: "QB",
    backgroundColor: "#46dee9",
  },
  "Daviyon Nixon": {
    name: "Daviyon Nixon",
    pick: 0,
    position: "IDL",
    backgroundColor: "#e4c390",
  },
  "Dax Milne": {
    name: "Dax Milne",
    pick: 0,
    position: "WR",
    backgroundColor: "#e94f25",
  },
  "Dayo Odeyingbo": {
    name: "Dayo Odeyingbo",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#0d0412",
  },
  "Dazz Newsome": {
    name: "Dazz Newsome",
    pick: 0,
    position: "WR",
    backgroundColor: "#260cb2",
  },
  "DeVonta Smith": {
    name: "DeVonta Smith",
    pick: 0,
    position: "WR",
    backgroundColor: "#da0bde",
  },
  "Dedrick Mills": {
    name: "Dedrick Mills",
    pick: 0,
    position: "RB",
    backgroundColor: "#640896",
  },
  "Demetric Felton": {
    name: "Demetric Felton",
    pick: 0,
    position: "WR",
    backgroundColor: "#756abf",
  },
  "Deommodore Lenoir": {
    name: "Deommodore Lenoir",
    pick: 0,
    position: "CB",
    backgroundColor: "#b283ab",
  },
  "Deon Jackson": {
    name: "Deon Jackson",
    pick: 0,
    position: "RB",
    backgroundColor: "#5fc61e",
  },
  "Deonte Brown": {
    name: "Deonte Brown",
    pick: 0,
    position: "IOL",
    backgroundColor: "#6d47cb",
  },
  "Derrick Barnes": {
    name: "Derrick Barnes",
    pick: 0,
    position: "LB",
    backgroundColor: "#1f6757",
  },
  "Devin Taylor": {
    name: "Devin Taylor",
    pick: 0,
    position: "CB",
    backgroundColor: "#267858",
  },
  "Dez Fitzpatrick": {
    name: "Dez Fitzpatrick",
    pick: 0,
    position: "WR",
    backgroundColor: "#580c26",
  },
  "Dicaprio Bootle": {
    name: "Dicaprio Bootle",
    pick: 0,
    position: "CB",
    backgroundColor: "#1948d4",
  },
  "Dillon Radunz": {
    name: "Dillon Radunz",
    pick: 0,
    position: "OT",
    backgroundColor: "#ba6f57",
  },
  "Dillon Stoner": {
    name: "Dillon Stoner",
    pick: 0,
    position: "WR",
    backgroundColor: "#109e4d",
  },
  "Divine Deablo": {
    name: "Divine Deablo",
    pick: 0,
    position: "S",
    backgroundColor: "#ab25dc",
  },
  "Donnie Corley": {
    name: "Donnie Corley",
    pick: 0,
    position: "WR",
    backgroundColor: "#b9f7a9",
  },
  "Dorian Etheridge": {
    name: "Dorian Etheridge",
    pick: 0,
    position: "LB",
    backgroundColor: "#ceb27c",
  },
  "Doug Kramer": {
    name: "Doug Kramer",
    pick: 0,
    position: "IOL",
    backgroundColor: "#1d03ea",
  },
  "Drake Jackson": {
    name: "Drake Jackson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#d5c9d9",
  },
  "Drew Dalman": {
    name: "Drew Dalman",
    pick: 0,
    position: "IOL",
    backgroundColor: "#7804f2",
  },
  "Drew Himmelman": {
    name: "Drew Himmelman",
    pick: 0,
    position: "OT",
    backgroundColor: "#570549",
  },
  "Dwayne Johnson Jr.": {
    name: "Dwayne Johnson Jr.",
    pick: 0,
    position: "S",
    backgroundColor: "#1fc852",
  },
  "Dyami Brown": {
    name: "Dyami Brown",
    pick: 0,
    position: "WR",
    backgroundColor: "#3a7a7e",
  },
  "Dylan Moses": {
    name: "Dylan Moses",
    pick: 0,
    position: "LB",
    backgroundColor: "#e131dc",
  },
  "Dylan Soehner": {
    name: "Dylan Soehner",
    pick: 0,
    position: "TE",
    backgroundColor: "#70d48b",
  },
  "Earnest Brown IV": {
    name: "Earnest Brown IV",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#28e766",
  },
  "Elerson Smith": {
    name: "Elerson Smith",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#fa345c",
  },
  "Eli Howard": {
    name: "Eli Howard",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#fe1d3b",
  },
  "Elijah Blades": {
    name: "Elijah Blades",
    pick: 0,
    position: "CB",
    backgroundColor: "#fa76ba",
  },
  "Elijah Mitchell": {
    name: "Elijah Mitchell",
    pick: 0,
    position: "RB",
    backgroundColor: "#b5dd6b",
  },
  "Elijah Molden": {
    name: "Elijah Molden",
    pick: 0,
    position: "CB",
    backgroundColor: "#0228a5",
  },
  "Elijah Moore": {
    name: "Elijah Moore",
    pick: 0,
    position: "WR",
    backgroundColor: "#e3437f",
  },
  "Elijah Ponder": {
    name: "Elijah Ponder",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#6ca79a",
  },
  "Emmanuel Jones": {
    name: "Emmanuel Jones",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#a708cb",
  },
  "Eric Burrell": {
    name: "Eric Burrell",
    pick: 0,
    position: "S",
    backgroundColor: "#597265",
  },
  "Eric Stokes": {
    name: "Eric Stokes",
    pick: 0,
    position: "CB",
    backgroundColor: "#63a358",
  },
  "Ernest Jones": {
    name: "Ernest Jones",
    pick: 0,
    position: "LB",
    backgroundColor: "#dc80c5",
  },
  "Erroll Thompson": {
    name: "Erroll Thompson",
    pick: 0,
    position: "LB",
    backgroundColor: "#02316d",
  },
  "Evan McPherson": {
    name: "Evan McPherson",
    pick: 0,
    position: "K",
    backgroundColor: "#939c3b",
  },
  "Feleipe Franks": {
    name: "Feleipe Franks",
    pick: 0,
    position: "QB",
    backgroundColor: "#2a3d2d",
  },
  "Forrest Merrill": {
    name: "Forrest Merrill",
    pick: 0,
    position: "IDL",
    backgroundColor: "#d85b97",
  },
  "Foster Sarell": {
    name: "Foster Sarell",
    pick: 0,
    position: "OT",
    backgroundColor: "#875d5b",
  },
  "Frank Darby": {
    name: "Frank Darby",
    pick: 0,
    position: "WR",
    backgroundColor: "#2fa16b",
  },
  "Franklin McCain III": {
    name: "Franklin McCain III",
    pick: 0,
    position: "CB",
    backgroundColor: "#c5f91f",
  },
  "Gabe Reid": {
    name: "Gabe Reid",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#e891d3",
  },
  "Garret Wallow": {
    name: "Garret Wallow",
    pick: 0,
    position: "LB",
    backgroundColor: "#1b4115",
  },
  "Garrett Groshek": {
    name: "Garrett Groshek",
    pick: 0,
    position: "RB",
    backgroundColor: "#e76de7",
  },
  "Gerrid Doaks": {
    name: "Gerrid Doaks",
    pick: 0,
    position: "RB",
    backgroundColor: "#89f087",
  },
  "Grant Hermanns": {
    name: "Grant Hermanns",
    pick: 0,
    position: "OT",
    backgroundColor: "#235cb5",
  },
  "Grant Stuard": {
    name: "Grant Stuard",
    pick: 0,
    position: "LB",
    backgroundColor: "#aa0b4b",
  },
  "Greg Eiland": {
    name: "Greg Eiland",
    pick: 0,
    position: "OT",
    backgroundColor: "#b42ada",
  },
  "Greg McCrae": {
    name: "Greg McCrae",
    pick: 0,
    position: "RB",
    backgroundColor: "#65cf5a",
  },
  "Greg Newsome II": {
    name: "Greg Newsome II",
    pick: 0,
    position: "CB",
    backgroundColor: "#25a6c3",
  },
  "Gregory Rousseau": {
    name: "Gregory Rousseau",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#d3468b",
  },
  "Hamilcar Rashed Jr.": {
    name: "Hamilcar Rashed Jr.",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#dff28f",
  },
  "Hamsah Nasirildeen": {
    name: "Hamsah Nasirildeen",
    pick: 0,
    position: "S",
    backgroundColor: "#70a935",
  },
  "Harry Crider": {
    name: "Harry Crider",
    pick: 0,
    position: "IOL",
    backgroundColor: "#95bdf0",
  },
  "Hunter Kampmoyer": {
    name: "Hunter Kampmoyer",
    pick: 0,
    position: "TE",
    backgroundColor: "#ae61e5",
  },
  "Hunter Long": {
    name: "Hunter Long",
    pick: 0,
    position: "TE",
    backgroundColor: "#5c7da1",
  },
  "Ian Book": {
    name: "Ian Book",
    pick: 0,
    position: "QB",
    backgroundColor: "#f17c6d",
  },
  "Ifeatu Melifonwu": {
    name: "Ifeatu Melifonwu",
    pick: 0,
    position: "CB",
    backgroundColor: "#6f36a5",
  },
  "Ihmir Smith-Marsette": {
    name: "Ihmir Smith-Marsette",
    pick: 0,
    position: "WR",
    backgroundColor: "#a9a472",
  },
  "Isaiah McDuffie": {
    name: "Isaiah McDuffie",
    pick: 0,
    position: "LB",
    backgroundColor: "#e5cbfe",
  },
  "Isaiah McKoy": {
    name: "Isaiah McKoy",
    pick: 0,
    position: "WR",
    backgroundColor: "#913e6f",
  },
  "Isaiahh Loudermilk": {
    name: "Isaiahh Loudermilk",
    pick: 0,
    position: "IDL",
    backgroundColor: "#0acb18",
  },
  "Israel Mukuamu": {
    name: "Israel Mukuamu",
    pick: 0,
    position: "CB",
    backgroundColor: "#4cabc3",
  },
  "Ja'Marr Chase": {
    name: "Ja'Marr Chase",
    pick: 0,
    position: "WR",
    backgroundColor: "#51743b",
  },
  "JaCoby Stevens": {
    name: "JaCoby Stevens",
    pick: 0,
    position: "S",
    backgroundColor: "#fa233f",
  },
  "JaQuan Bailey": {
    name: "JaQuan Bailey",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#5d69b5",
  },
  "Jabril Cox": {
    name: "Jabril Cox",
    pick: 0,
    position: "LB",
    backgroundColor: "#e10ad6",
  },
  "Jack Anderson": {
    name: "Jack Anderson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#b62f7b",
  },
  "Jack Stoll": {
    name: "Jack Stoll",
    pick: 0,
    position: "TE",
    backgroundColor: "#c25654",
  },
  "Jackson Carman": {
    name: "Jackson Carman",
    pick: 0,
    position: "OT",
    backgroundColor: "#2f35af",
  },
  "Jaelan Phillips": {
    name: "Jaelan Phillips",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#121f61",
  },
  "Jaelon Darden": {
    name: "Jaelon Darden",
    pick: 0,
    position: "WR",
    backgroundColor: "#1ad6a5",
  },
  "Jah-Maine Martin": {
    name: "Jah-Maine Martin",
    pick: 0,
    position: "RB",
    backgroundColor: "#410138",
  },
  "Jake Curhan": {
    name: "Jake Curhan",
    pick: 0,
    position: "IOL",
    backgroundColor: "#d13cfa",
  },
  "Jake Funk": {
    name: "Jake Funk",
    pick: 0,
    position: "RB",
    backgroundColor: "#079e68",
  },
  "Jalen Mayfield": {
    name: "Jalen Mayfield",
    pick: 0,
    position: "OT",
    backgroundColor: "#fa9fec",
  },
  "Jamar Johnson": {
    name: "Jamar Johnson",
    pick: 0,
    position: "S",
    backgroundColor: "#16731e",
  },
  "Jamar Watson": {
    name: "Jamar Watson",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#40152b",
  },
  "James Hudson": {
    name: "James Hudson",
    pick: 0,
    position: "OT",
    backgroundColor: "#4c76bd",
  },
  "James Smith": {
    name: "James Smith",
    pick: 0,
    position: "P",
    backgroundColor: "#ddea83",
  },
  "James Wiggins": {
    name: "James Wiggins",
    pick: 0,
    position: "S",
    backgroundColor: "#e44ad6",
  },
  "Jamie Newman": {
    name: "Jamie Newman",
    pick: 0,
    position: "QB",
    backgroundColor: "#05082d",
  },
  "Jamien Sherwood": {
    name: "Jamien Sherwood",
    pick: 0,
    position: "S",
    backgroundColor: "#92a08f",
  },
  "Jamin Davis": {
    name: "Jamin Davis",
    pick: 0,
    position: "LB",
    backgroundColor: "#a66d96",
  },
  "Janarius Robinson": {
    name: "Janarius Robinson",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#687ce1",
  },
  "Jared Hocker": {
    name: "Jared Hocker",
    pick: 0,
    position: "IOL",
    backgroundColor: "#ed6cc7",
  },
  "Jaret Patterson": {
    name: "Jaret Patterson",
    pick: 0,
    position: "RB",
    backgroundColor: "#d866bc",
  },
  "Jarrod Hewitt": {
    name: "Jarrod Hewitt",
    pick: 0,
    position: "IDL",
    backgroundColor: "#31a61d",
  },
  "Javian Hawkins": {
    name: "Javian Hawkins",
    pick: 0,
    position: "RB",
    backgroundColor: "#18dfff",
  },
  "Javon McKinley": {
    name: "Javon McKinley",
    pick: 0,
    position: "WR",
    backgroundColor: "#7b77c2",
  },
  "Javonte Williams": {
    name: "Javonte Williams",
    pick: 0,
    position: "RB",
    backgroundColor: "#18da7a",
  },
  "Jay Tufele": {
    name: "Jay Tufele",
    pick: 0,
    position: "IDL",
    backgroundColor: "#a2f260",
  },
  "Jaycee Horn": {
    name: "Jaycee Horn",
    pick: 0,
    position: "CB",
    backgroundColor: "#a05e35",
  },
  "Jaylen Twyman": {
    name: "Jaylen Twyman",
    pick: 0,
    position: "IDL",
    backgroundColor: "#1b1253",
  },
  "Jaylen Waddle": {
    name: "Jaylen Waddle",
    pick: 0,
    position: "WR",
    backgroundColor: "#5fda2d",
  },
  "Jaylon Moore": {
    name: "Jaylon Moore",
    pick: 0,
    position: "OT",
    backgroundColor: "#eefed9",
  },
  "Jayson Oweh": {
    name: "Jayson Oweh",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#5d0a60",
  },
  "Jeremiah Owusu-Koramoah": {
    name: "Jeremiah Owusu-Koramoah",
    pick: 0,
    position: "LB",
    backgroundColor: "#1aceed",
  },
  "Jermar Jefferson": {
    name: "Jermar Jefferson",
    pick: 0,
    position: "RB",
    backgroundColor: "#5d579f",
  },
  "Jerry Jacobs": {
    name: "Jerry Jacobs",
    pick: 0,
    position: "CB",
    backgroundColor: "#ab5b3b",
  },
  "Jevon Holland": {
    name: "Jevon Holland",
    pick: 0,
    position: "S",
    backgroundColor: "#46d9c9",
  },
  "Jhamon Ausbon": {
    name: "Jhamon Ausbon",
    pick: 0,
    position: "WR",
    backgroundColor: "#1a2a6e",
  },
  "Jimmy Morrissey": {
    name: "Jimmy Morrissey",
    pick: 0,
    position: "IOL",
    backgroundColor: "#de49e7",
  },
  "Joe Black": {
    name: "Joe Black",
    pick: 0,
    position: "IOL",
    backgroundColor: "#8c8615",
  },
  "Joe Tryon": {
    name: "Joe Tryon",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#11e307",
  },
  "John Bates": {
    name: "John Bates",
    pick: 0,
    position: "TE",
    backgroundColor: "#17123d",
  },
  "Jonathan Adams Jr.": {
    name: "Jonathan Adams Jr.",
    pick: 0,
    position: "WR",
    backgroundColor: "#4bf2b5",
  },
  "Jonathan Marshall": {
    name: "Jonathan Marshall",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#2d7b43",
  },
  "Jonathon Cooper": {
    name: "Jonathon Cooper",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#37ed51",
  },
  "Jordan Fox": {
    name: "Jordan Fox",
    pick: 0,
    position: "LB",
    backgroundColor: "#2a2f15",
  },
  "Jordan Jackson": {
    name: "Jordan Jackson",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#b0d5cc",
  },
  "Jordan Smith": {
    name: "Jordan Smith",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#f5628f",
  },
  "Jordon Scott": {
    name: "Jordon Scott",
    pick: 0,
    position: "IDL",
    backgroundColor: "#4342f7",
  },
  "Jose Borregales": {
    name: "Jose Borregales",
    pick: 0,
    position: "K",
    backgroundColor: "#1cfffb",
  },
  "Joseph Ossai": {
    name: "Joseph Ossai",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#b832d4",
  },
  "Josh Ball": {
    name: "Josh Ball",
    pick: 0,
    position: "OT",
    backgroundColor: "#0b5e53",
  },
  "Josh Imatorbhebhe": {
    name: "Josh Imatorbhebhe",
    pick: 0,
    position: "WR",
    backgroundColor: "#8bb85a",
  },
  "Josh Myers": {
    name: "Josh Myers",
    pick: 0,
    position: "IOL",
    backgroundColor: "#97ea7a",
  },
  "Josh Palmer": {
    name: "Josh Palmer",
    pick: 0,
    position: "WR",
    backgroundColor: "#12e0e3",
  },
  "Joshua Fedd-Jackson": {
    name: "Joshua Fedd-Jackson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#db792b",
  },
  "Joshua Kaindoh": {
    name: "Joshua Kaindoh",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#91f276",
  },
  "Joshua Ross": {
    name: "Joshua Ross",
    pick: 0,
    position: "LB",
    backgroundColor: "#070306",
  },
  "Joshuah Bledsoe": {
    name: "Joshuah Bledsoe",
    pick: 0,
    position: "S",
    backgroundColor: "#bdba79",
  },
  "Josiah Bronson": {
    name: "Josiah Bronson",
    pick: 0,
    position: "IDL",
    backgroundColor: "#3637d8",
  },
  "Justin Fields": {
    name: "Justin Fields",
    pick: 0,
    position: "QB",
    backgroundColor: "#c7783c",
  },
  "Justin Hilliard": {
    name: "Justin Hilliard",
    pick: 0,
    position: "LB",
    backgroundColor: "#aebd4c",
  },
  "Justus Reed": {
    name: "Justus Reed",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#d89a70",
  },
  "K.D. Nixon": {
    name: "K.D. Nixon",
    pick: 0,
    position: "WR",
    backgroundColor: "#57481d",
  },
  "K.J. Britt": {
    name: "K.J. Britt",
    pick: 0,
    position: "LB",
    backgroundColor: "#7dcf50",
  },
  "K.J. Costello": {
    name: "K.J. Costello",
    pick: 0,
    position: "QB",
    backgroundColor: "#bb1f5b",
  },
  "Kadarius Toney": {
    name: "Kadarius Toney",
    pick: 0,
    position: "WR",
    backgroundColor: "#665bcb",
  },
  "Kary Vincent Jr.": {
    name: "Kary Vincent Jr.",
    pick: 0,
    position: "CB",
    backgroundColor: "#cd0a58",
  },
  "Kayode Awosika": {
    name: "Kayode Awosika",
    pick: 0,
    position: "OT",
    backgroundColor: "#4205cb",
  },
  "Keith Taylor Jr.": {
    name: "Keith Taylor Jr.",
    pick: 0,
    position: "CB",
    backgroundColor: "#6a95f1",
  },
  "Kellen Mond": {
    name: "Kellen Mond",
    pick: 0,
    position: "QB",
    backgroundColor: "#4ae50a",
  },
  "Kelvin Joseph": {
    name: "Kelvin Joseph",
    pick: 0,
    position: "CB",
    backgroundColor: "#2061b0",
  },
  "Kendrick Green": {
    name: "Kendrick Green",
    pick: 0,
    position: "IOL",
    backgroundColor: "#2bf858",
  },
  "Kenneth Gainwell": {
    name: "Kenneth Gainwell",
    pick: 0,
    position: "RB",
    backgroundColor: "#b7d8b9",
  },
  "Kenny Yeboah": {
    name: "Kenny Yeboah",
    pick: 0,
    position: "TE",
    backgroundColor: "#9f0dfd",
  },
  "Khalil Herbert": {
    name: "Khalil Herbert",
    pick: 0,
    position: "RB",
    backgroundColor: "#c3d507",
  },
  "Khyiris Tonga": {
    name: "Khyiris Tonga",
    pick: 0,
    position: "IDL",
    backgroundColor: "#2b0ca7",
  },
  "Kobe Jones": {
    name: "Kobe Jones",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#e1720f",
  },
  "Kwity Paye": {
    name: "Kwity Paye",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#bdf6c5",
  },
  "Ky'El Hemby": {
    name: "Ky'El Hemby",
    pick: 0,
    position: "S",
    backgroundColor: "#e4bf1a",
  },
  "Kyle Pitts": {
    name: "Kyle Pitts",
    pick: 0,
    position: "TE",
    backgroundColor: "#6a360d",
  },
  "Kyle Trask": {
    name: "Kyle Trask",
    pick: 0,
    position: "QB",
    backgroundColor: "#da3fe8",
  },
  "Kylen Granson": {
    name: "Kylen Granson",
    pick: 0,
    position: "TE",
    backgroundColor: "#31e080",
  },
  "Kylin Hill": {
    name: "Kylin Hill",
    pick: 0,
    position: "RB",
    backgroundColor: "#177569",
  },
  "Lamont Wade": {
    name: "Lamont Wade",
    pick: 0,
    position: "S",
    backgroundColor: "#94d280",
  },
  "Landon Dickerson": {
    name: "Landon Dickerson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#4dae46",
  },
  "Landon Young": {
    name: "Landon Young",
    pick: 0,
    position: "OT",
    backgroundColor: "#2a9510",
  },
  "Larry Borom": {
    name: "Larry Borom",
    pick: 0,
    position: "IOL",
    backgroundColor: "#860a4f",
  },
  "Larry Rountree III": {
    name: "Larry Rountree III",
    pick: 0,
    position: "RB",
    backgroundColor: "#bfb897",
  },
  "Levi Onwuzurike": {
    name: "Levi Onwuzurike",
    pick: 0,
    position: "IDL",
    backgroundColor: "#949c24",
  },
  "Liam Eichenberg": {
    name: "Liam Eichenberg",
    pick: 0,
    position: "OT",
    backgroundColor: "#e42e56",
  },
  "Lorenzo Burns": {
    name: "Lorenzo Burns",
    pick: 0,
    position: "CB",
    backgroundColor: "#76f4b8",
  },
  "Luke Farrell": {
    name: "Luke Farrell",
    pick: 0,
    position: "TE",
    backgroundColor: "#56ebff",
  },
  "Luke Fortner": {
    name: "Luke Fortner",
    pick: 0,
    position: "IOL",
    backgroundColor: "#2fc7bd",
  },
  "Mac Jones": {
    name: "Mac Jones",
    pick: 0,
    position: "QB",
    backgroundColor: "#08271e",
  },
  "Malcolm Koonce": {
    name: "Malcolm Koonce",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#1248cf",
  },
  "Malik Herring": {
    name: "Malik Herring",
    pick: 0,
    position: "IDL",
    backgroundColor: "#fc0178",
  },
  "Manny Rugamba": {
    name: "Manny Rugamba",
    pick: 0,
    position: "CB",
    backgroundColor: "#b27633",
  },
  "Marco Wilson": {
    name: "Marco Wilson",
    pick: 0,
    position: "CB",
    backgroundColor: "#3a69a3",
  },
  "Mark Gilbert": {
    name: "Mark Gilbert",
    pick: 0,
    position: "CB",
    backgroundColor: "#3ee727",
  },
  "Mark Webb": {
    name: "Mark Webb",
    pick: 0,
    position: "S",
    backgroundColor: "#f21c0f",
  },
  "Marlon Tuipulotu": {
    name: "Marlon Tuipulotu",
    pick: 0,
    position: "IDL",
    backgroundColor: "#6f7463",
  },
  "Marlon Williams": {
    name: "Marlon Williams",
    pick: 0,
    position: "WR",
    backgroundColor: "#899e64",
  },
  "Marquez Stevenson": {
    name: "Marquez Stevenson",
    pick: 0,
    position: "WR",
    backgroundColor: "#d027bf",
  },
  "Marvin Wilson": {
    name: "Marvin Wilson",
    pick: 0,
    position: "IDL",
    backgroundColor: "#d59c00",
  },
  "Matt Bushman": {
    name: "Matt Bushman",
    pick: 0,
    position: "TE",
    backgroundColor: "#b626ee",
  },
  "Max Duffy": {
    name: "Max Duffy",
    pick: 0,
    position: "P",
    backgroundColor: "#0e3068",
  },
  "Mekhi Sargent": {
    name: "Mekhi Sargent",
    pick: 0,
    position: "RB",
    backgroundColor: "#f7ff00",
  },
  "Micah Parsons": {
    name: "Micah Parsons",
    pick: 0,
    position: "LB",
    backgroundColor: "#31c9fc",
  },
  "Michael Boykin": {
    name: "Michael Boykin",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#2416b9",
  },
  "Michael Carter": {
    name: "Michael Carter",
    pick: 0,
    position: "RB",
    backgroundColor: "#78cb5d",
  },
  "Michael Strachan": {
    name: "Michael Strachan",
    pick: 0,
    position: "WR",
    backgroundColor: "#bee1bd",
  },
  "Michal Menet": {
    name: "Michal Menet",
    pick: 0,
    position: "IOL",
    backgroundColor: "#8f772b",
  },
  "Mike Hampton": {
    name: "Mike Hampton",
    pick: 0,
    position: "CB",
    backgroundColor: "#e7f56e",
  },
  "Miller Forristall": {
    name: "Miller Forristall",
    pick: 0,
    position: "TE",
    backgroundColor: "#760972",
  },
  "Milo Eifler": {
    name: "Milo Eifler",
    pick: 0,
    position: "LB",
    backgroundColor: "#228252",
  },
  "Milton Williams": {
    name: "Milton Williams",
    pick: 0,
    position: "IDL",
    backgroundColor: "#c98902",
  },
  "Monty Rice": {
    name: "Monty Rice",
    pick: 0,
    position: "LB",
    backgroundColor: "#431f3a",
  },
  "Mustafa Johnson": {
    name: "Mustafa Johnson",
    pick: 0,
    position: "IDL",
    backgroundColor: "#7ee665",
  },
  "Myron Mitchell": {
    name: "Myron Mitchell",
    pick: 0,
    position: "WR",
    backgroundColor: "#1b5752",
  },
  "Myron Tagovailoa-Amosa": {
    name: "Myron Tagovailoa-Amosa",
    pick: 0,
    position: "IDL",
    backgroundColor: "#e1a69c",
  },
  "Nahshon Wright": {
    name: "Nahshon Wright",
    pick: 0,
    position: "CB",
    backgroundColor: "#a969fa",
  },
  "Najee Harris": {
    name: "Najee Harris",
    pick: 0,
    position: "RB",
    backgroundColor: "#632da0",
  },
  "Naquan Jones": {
    name: "Naquan Jones",
    pick: 0,
    position: "IDL",
    backgroundColor: "#1fb1a7",
  },
  "Nate Hobbs": {
    name: "Nate Hobbs",
    pick: 0,
    position: "CB",
    backgroundColor: "#9c694a",
  },
  "Nick Bolton": {
    name: "Nick Bolton",
    pick: 0,
    position: "LB",
    backgroundColor: "#8d4b8e",
  },
  "Nick Eubanks": {
    name: "Nick Eubanks",
    pick: 0,
    position: "TE",
    backgroundColor: "#dac7c1",
  },
  "Nick Pickett": {
    name: "Nick Pickett",
    pick: 0,
    position: "S",
    backgroundColor: "#c4cabd",
  },
  "Nico Collins": {
    name: "Nico Collins",
    pick: 0,
    position: "WR",
    backgroundColor: "#68fb5b",
  },
  "Noah Gray": {
    name: "Noah Gray",
    pick: 0,
    position: "TE",
    backgroundColor: "#176805",
  },
  "Olaijah Griffin": {
    name: "Olaijah Griffin",
    pick: 0,
    position: "CB",
    backgroundColor: "#97f2d7",
  },
  "Osa Odighizuwa": {
    name: "Osa Odighizuwa",
    pick: 0,
    position: "IDL",
    backgroundColor: "#406b65",
  },
  "Osirus Mitchell": {
    name: "Osirus Mitchell",
    pick: 0,
    position: "WR",
    backgroundColor: "#8d9939",
  },
  "Otis Anderson": {
    name: "Otis Anderson",
    pick: 0,
    position: "RB",
    backgroundColor: "#8dda01",
  },
  "Paddy Fisher": {
    name: "Paddy Fisher",
    pick: 0,
    position: "LB",
    backgroundColor: "#ded215",
  },
  "Paris Ford": {
    name: "Paris Ford",
    pick: 0,
    position: "S",
    backgroundColor: "#8b5f96",
  },
  "Pat Freiermuth": {
    name: "Pat Freiermuth",
    pick: 0,
    position: "TE",
    backgroundColor: "#230105",
  },
  "Patrick Johnson": {
    name: "Patrick Johnson",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#02dd9b",
  },
  "Patrick Jones II": {
    name: "Patrick Jones II",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#9b28aa",
  },
  "Patrick Surtain II": {
    name: "Patrick Surtain II",
    pick: 0,
    position: "CB",
    backgroundColor: "#b42c5c",
  },
  "Paul Grattan": {
    name: "Paul Grattan",
    pick: 0,
    position: "IOL",
    backgroundColor: "#c1cd6e",
  },
  "Paulson Adebo": {
    name: "Paulson Adebo",
    pick: 0,
    position: "CB",
    backgroundColor: "#971628",
  },
  "Payton Turner": {
    name: "Payton Turner",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#182829",
  },
  "Penei Sewell": {
    name: "Penei Sewell",
    pick: 0,
    position: "OT",
    backgroundColor: "#eaf08c",
  },
  "Pete Werner": {
    name: "Pete Werner",
    pick: 0,
    position: "LB",
    backgroundColor: "#009f73",
  },
  "Peyton Ramsey": {
    name: "Peyton Ramsey",
    pick: 0,
    position: "QB",
    backgroundColor: "#c662dd",
  },
  "Pooka Williams": {
    name: "Pooka Williams",
    pick: 0,
    position: "RB",
    backgroundColor: "#13cbf1",
  },
  "Pro Wells": {
    name: "Pro Wells",
    pick: 0,
    position: "TE",
    backgroundColor: "#efa0ec",
  },
  "Quincy Roche": {
    name: "Quincy Roche",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#dd82f5",
  },
  "Quinn Meinerz": {
    name: "Quinn Meinerz",
    pick: 0,
    position: "IOL",
    backgroundColor: "#72806d",
  },
  "Quintin Morris": {
    name: "Quintin Morris",
    pick: 0,
    position: "TE",
    backgroundColor: "#b76654",
  },
  "Quinton Bohanna": {
    name: "Quinton Bohanna",
    pick: 0,
    position: "IDL",
    backgroundColor: "#9817ff",
  },
  "Qwynnterrio Cole": {
    name: "Qwynnterrio Cole",
    pick: 0,
    position: "S",
    backgroundColor: "#7baacf",
  },
  "Racey McMath": {
    name: "Racey McMath",
    pick: 0,
    position: "WR",
    backgroundColor: "#ef590f",
  },
  "Rachad Wildgoose Jr.": {
    name: "Rachad Wildgoose Jr.",
    pick: 0,
    position: "CB",
    backgroundColor: "#6ab3f7",
  },
  "Rakeem Boyd": {
    name: "Rakeem Boyd",
    pick: 0,
    position: "RB",
    backgroundColor: "#3cc7e4",
  },
  "Rashad Weaver": {
    name: "Rashad Weaver",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#ef7517",
  },
  "Rashawn Slater": {
    name: "Rashawn Slater",
    pick: 0,
    position: "OT",
    backgroundColor: "#ddee58",
  },
  "Rashod Bateman": {
    name: "Rashod Bateman",
    pick: 0,
    position: "WR",
    backgroundColor: "#9c0f31",
  },
  "Rayshard Ashby": {
    name: "Rayshard Ashby",
    pick: 0,
    position: "LB",
    backgroundColor: "#7c895e",
  },
  "Rhamondre Stevenson": {
    name: "Rhamondre Stevenson",
    pick: 0,
    position: "RB",
    backgroundColor: "#9e51c5",
  },
  "Richard LeCounte III": {
    name: "Richard LeCounte III",
    pick: 0,
    position: "S",
    backgroundColor: "#241ad7",
  },
  "Richie Grant": {
    name: "Richie Grant",
    pick: 0,
    position: "S",
    backgroundColor: "#03c058",
  },
  "Rico Bussey Jr.": {
    name: "Rico Bussey Jr.",
    pick: 0,
    position: "WR",
    backgroundColor: "#a9a51f",
  },
  "Riley Cole": {
    name: "Riley Cole",
    pick: 0,
    position: "LB",
    backgroundColor: "#772296",
  },
  "Robert Hainsey": {
    name: "Robert Hainsey",
    pick: 0,
    position: "OT",
    backgroundColor: "#2a639b",
  },
  "Robert Jones": {
    name: "Robert Jones",
    pick: 0,
    position: "IOL",
    backgroundColor: "#dcd534",
  },
  "Robert Rochell": {
    name: "Robert Rochell",
    pick: 0,
    position: "CB",
    backgroundColor: "#f24213",
  },
  "Rodarius Williams": {
    name: "Rodarius Williams",
    pick: 0,
    position: "CB",
    backgroundColor: "#1ef3bf",
  },
  "Romeo McKnight": {
    name: "Romeo McKnight",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#7fdd15",
  },
  "Rondale Moore": {
    name: "Rondale Moore",
    pick: 0,
    position: "WR",
    backgroundColor: "#0e0fd0",
  },
  "Ronnie Perkins": {
    name: "Ronnie Perkins",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#0dbf97",
  },
  "Roy Lopez": {
    name: "Roy Lopez",
    pick: 0,
    position: "IDL",
    backgroundColor: "#3c3876",
  },
  "Royce Newman": {
    name: "Royce Newman",
    pick: 0,
    position: "OT",
    backgroundColor: "#841691",
  },
  "Ryan McCollum": {
    name: "Ryan McCollum",
    pick: 0,
    position: "IOL",
    backgroundColor: "#4e6567",
  },
  "Sadarius Hutcherson": {
    name: "Sadarius Hutcherson",
    pick: 0,
    position: "IOL",
    backgroundColor: "#55fa56",
  },
  "Sage Surratt": {
    name: "Sage Surratt",
    pick: 0,
    position: "WR",
    backgroundColor: "#7c75ec",
  },
  "Sam Ehlinger": {
    name: "Sam Ehlinger",
    pick: 0,
    position: "QB",
    backgroundColor: "#4546f9",
  },
  "Sam Williams": {
    name: "Sam Williams",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#e93093",
  },
  "Samuel Cooper � Merrimack": {
    name: "Samuel Cooper � Merrimack",
    pick: 0,
    position: "IOL",
    backgroundColor: "#c2d699",
  },
  "Samuel Cosmi": {
    name: "Samuel Cosmi",
    pick: 0,
    position: "OT",
    backgroundColor: "#c8a761",
  },
  "Seth Williams": {
    name: "Seth Williams",
    pick: 0,
    position: "WR",
    backgroundColor: "#666628",
  },
  "Shaka Toney": {
    name: "Shaka Toney",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#575952",
  },
  "Shakur Brown": {
    name: "Shakur Brown",
    pick: 0,
    position: "CB",
    backgroundColor: "#08c4d7",
  },
  "Shane Buechele": {
    name: "Shane Buechele",
    pick: 0,
    position: "QB",
    backgroundColor: "#2212fc",
  },
  "Shaun Beyer": {
    name: "Shaun Beyer",
    pick: 0,
    position: "TE",
    backgroundColor: "#707d25",
  },
  "Shaun Wade": {
    name: "Shaun Wade",
    pick: 0,
    position: "CB",
    backgroundColor: "#4ead58",
  },
  "Shawn Davis": {
    name: "Shawn Davis",
    pick: 0,
    position: "S",
    backgroundColor: "#edd6be",
  },
  "Shemar Jean-Charles": {
    name: "Shemar Jean-Charles",
    pick: 0,
    position: "CB",
    backgroundColor: "#c26603",
  },
  "Shi Smith": {
    name: "Shi Smith",
    pick: 0,
    position: "WR",
    backgroundColor: "#c18910",
  },
  "Simi Fehoko": {
    name: "Simi Fehoko",
    pick: 0,
    position: "WR",
    backgroundColor: "#a2b89e",
  },
  "Spencer Brown": {
    name: "Spencer Brown",
    pick: 0,
    position: "RB",
    backgroundColor: "#c11b7c",
  },
  "Stevie Scott III": {
    name: "Stevie Scott III",
    pick: 0,
    position: "RB",
    backgroundColor: "#49c016",
  },
  "Stone Forsythe": {
    name: "Stone Forsythe",
    pick: 0,
    position: "OT",
    backgroundColor: "#94e320",
  },
  "T.J. Vasher": {
    name: "T.J. Vasher",
    pick: 0,
    position: "WR",
    backgroundColor: "#f99e16",
  },
  "Ta'Quon Graham": {
    name: "Ta'Quon Graham",
    pick: 0,
    position: "IDL",
    backgroundColor: "#ff074b",
  },
  "Taaga Tuulima": {
    name: "Taaga Tuulima",
    pick: 0,
    position: "IOL",
    backgroundColor: "#86125d",
  },
  "Talanoa Hufanga": {
    name: "Talanoa Hufanga",
    pick: 0,
    position: "S",
    backgroundColor: "#bd6683",
  },
  "Tamorrion Terry": {
    name: "Tamorrion Terry",
    pick: 0,
    position: "WR",
    backgroundColor: "#8dd8b7",
  },
  "Tarik Black": {
    name: "Tarik Black",
    pick: 0,
    position: "WR",
    backgroundColor: "#593867",
  },
  "Tariq Thompson": {
    name: "Tariq Thompson",
    pick: 0,
    position: "S",
    backgroundColor: "#883f00",
  },
  "Tarron Jackson": {
    name: "Tarron Jackson",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#25fbd7",
  },
  "Tay Gowan": {
    name: "Tay Gowan",
    pick: 0,
    position: "CB",
    backgroundColor: "#16aad6",
  },
  "Tedarrell Slaton": {
    name: "Tedarrell Slaton",
    pick: 0,
    position: "IDL",
    backgroundColor: "#b21357",
  },
  "Terrace Marshall Jr.": {
    name: "Terrace Marshall Jr.",
    pick: 0,
    position: "WR",
    backgroundColor: "#f0f127",
  },
  "Teven Jenkins": {
    name: "Teven Jenkins",
    pick: 0,
    position: "OT",
    backgroundColor: "#7c6e1c",
  },
  "Thomas Graham Jr.": {
    name: "Thomas Graham Jr.",
    pick: 0,
    position: "CB",
    backgroundColor: "#6265d7",
  },
  "Tim Jones": {
    name: "Tim Jones",
    pick: 0,
    position: "WR",
    backgroundColor: "#32e7e3",
  },
  "Tommy Doyle": {
    name: "Tommy Doyle",
    pick: 0,
    position: "OT",
    backgroundColor: "#0edc6f",
  },
  "Tommy Kraemer": {
    name: "Tommy Kraemer",
    pick: 0,
    position: "IOL",
    backgroundColor: "#8439f0",
  },
  "Tommy Togiai": {
    name: "Tommy Togiai",
    pick: 0,
    position: "IDL",
    backgroundColor: "#c102b1",
  },
  "Tommy Tremble": {
    name: "Tommy Tremble",
    pick: 0,
    position: "TE",
    backgroundColor: "#de9a7b",
  },
  "Tony Fields II": {
    name: "Tony Fields II",
    pick: 0,
    position: "LB",
    backgroundColor: "#92fb31",
  },
  "Tony Poljan": {
    name: "Tony Poljan",
    pick: 0,
    position: "TE",
    backgroundColor: "#887560",
  },
  "Travis Etienne": {
    name: "Travis Etienne",
    pick: 0,
    position: "RB",
    backgroundColor: "#501b02",
  },
  "Tre Brown": {
    name: "Tre Brown",
    pick: 0,
    position: "CB",
    backgroundColor: "#9d6aef",
  },
  "Tre Harbison": {
    name: "Tre Harbison",
    pick: 0,
    position: "RB",
    backgroundColor: "#e79dd7",
  },
  "Tre Nixon": {
    name: "Tre Nixon",
    pick: 0,
    position: "WR",
    backgroundColor: "#19337f",
  },
  "Tre Norwood": {
    name: "Tre Norwood",
    pick: 0,
    position: "CB",
    backgroundColor: "#056a01",
  },
  "Tre Walker": {
    name: "Tre Walker",
    pick: 0,
    position: "WR",
    backgroundColor: "#176971",
  },
  "Tre' McKitty": {
    name: "Tre' McKitty",
    pick: 0,
    position: "TE",
    backgroundColor: "#2d4dc8",
  },
  "Trevon Grimes": {
    name: "Trevon Grimes",
    pick: 0,
    position: "WR",
    backgroundColor: "#4bcd7b",
  },
  "Trevon Moehrig": {
    name: "Trevon Moehrig",
    pick: 0,
    position: "S",
    backgroundColor: "#378f10",
  },
  "Trevor Lawrence": {
    name: "Trevor Lawrence",
    pick: 0,
    position: "QB",
    backgroundColor: "#196fba",
  },
  "Trey Hill": {
    name: "Trey Hill",
    pick: 0,
    position: "IOL",
    backgroundColor: "#3d04ab",
  },
  "Trey Lance": {
    name: "Trey Lance",
    pick: 0,
    position: "QB",
    backgroundColor: "#b2eb70",
  },
  "Trey Ragas": {
    name: "Trey Ragas",
    pick: 0,
    position: "RB",
    backgroundColor: "#331d06",
  },
  "Trey Sermon": {
    name: "Trey Sermon",
    pick: 0,
    position: "RB",
    backgroundColor: "#968991",
  },
  "Trey Smith": {
    name: "Trey Smith",
    pick: 0,
    position: "IOL",
    backgroundColor: "#bcf5a1",
  },
  "Trill Williams": {
    name: "Trill Williams",
    pick: 0,
    position: "CB",
    backgroundColor: "#d06d4b",
  },
  "Tristen Hoge": {
    name: "Tristen Hoge",
    pick: 0,
    position: "IOL",
    backgroundColor: "#5e3349",
  },
  "Tuf Borland": {
    name: "Tuf Borland",
    pick: 0,
    position: "LB",
    backgroundColor: "#ff533b",
  },
  "Tylan Wallace": {
    name: "Tylan Wallace",
    pick: 0,
    position: "WR",
    backgroundColor: "#fb11c2",
  },
  "Tyler Coyle": {
    name: "Tyler Coyle",
    pick: 0,
    position: "S",
    backgroundColor: "#0fec0e",
  },
  "Tyler Shelvin": {
    name: "Tyler Shelvin",
    pick: 0,
    position: "IDL",
    backgroundColor: "#257c96",
  },
  "Tyler Vaughns": {
    name: "Tyler Vaughns",
    pick: 0,
    position: "WR",
    backgroundColor: "#01ebf4",
  },
  "Tyree Gillespie": {
    name: "Tyree Gillespie",
    pick: 0,
    position: "S",
    backgroundColor: "#bab7f8",
  },
  "Tyson Campbell": {
    name: "Tyson Campbell",
    pick: 0,
    position: "CB",
    backgroundColor: "#ed4fd9",
  },
  "Vavae Malepeai": {
    name: "Vavae Malepeai",
    pick: 0,
    position: "RB",
    backgroundColor: "#168322",
  },
  "Victor Dimukeje": {
    name: "Victor Dimukeje",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#b53b0a",
  },
  "Walker Little": {
    name: "Walker Little",
    pick: 0,
    position: "OT",
    backgroundColor: "#b03c9d",
  },
  "Warren Jackson": {
    name: "Warren Jackson",
    pick: 0,
    position: "WR",
    backgroundColor: "#b3db71",
  },
  "Whop Philyor": {
    name: "Whop Philyor",
    pick: 0,
    position: "WR",
    backgroundColor: "#773a00",
  },
  "Will Fries": {
    name: "Will Fries",
    pick: 0,
    position: "OT",
    backgroundColor: "#4f2e08",
  },
  "William Bradley-King": {
    name: "William Bradley-King",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#afd38b",
  },
  "Wyatt Davis": {
    name: "Wyatt Davis",
    pick: 0,
    position: "IOL",
    backgroundColor: "#5c55db",
  },
  "Wyatt Hubert": {
    name: "Wyatt Hubert",
    pick: 0,
    position: "EDGE",
    backgroundColor: "#70abed",
  },
  "Xavier Kelly": {
    name: "Xavier Kelly",
    pick: 0,
    position: "IDL",
    backgroundColor: "#4da480",
  },
  "Zac Thomas": {
    name: "Zac Thomas",
    pick: 0,
    position: "QB",
    backgroundColor: "#c3d3f2",
  },
  "Zach Davidson": {
    name: "Zach Davidson",
    pick: 0,
    position: "TE",
    backgroundColor: "#f5c4ab",
  },
  "Zach Smith": {
    name: "Zach Smith",
    pick: 0,
    position: "QB",
    backgroundColor: "#2fde5d",
  },
  "Zach Wilson": {
    name: "Zach Wilson",
    pick: 0,
    position: "QB",
    backgroundColor: "#7c0652",
  },
  "Zachary Thomas": {
    name: "Zachary Thomas",
    pick: 0,
    position: "IOL",
    backgroundColor: "#4585ec",
  },
  "Zaven Collins": {
    name: "Zaven Collins",
    pick: 0,
    position: "LB",
    backgroundColor: "#a84239",
  },
  "Zayne Anderson": {
    name: "Zayne Anderson",
    pick: 0,
    position: "S",
    backgroundColor: "#7e020d",
  },
  "Zeandae Johnson": {
    name: "Zeandae Johnson",
    pick: 0,
    position: "IDL",
    backgroundColor: "#50ed48",
  },
  "Zech McPhearson": {
    name: "Zech McPhearson",
    pick: 0,
    position: "CB",
    backgroundColor: "#5eebdf",
  },
};

export default players;
