const teamSubreddits = {
  "49ers": "49ers",
  Bears: "CHIBears",
  Bengals: "bengals",
  Bills: "buffalobills",
  Broncos: "DenverBroncos",
  Browns: "Browns",
  Buccaneers: "buccaneers",
  Cardinals: "AZCardinals",
  Chargers: "Chargers",
  Chiefs: "KansasCityChiefs",
  Colts: "Colts",
  Cowboys: "cowboys",
  Dolphins: "miamidolphins",
  Eagles: "eagles",
  Falcons: "falcons",
  "Football Team": "washingtonNFL",
  Giants: "NYGiants",
  Jaguars: "Jaguars",
  Jets: "nyjets",
  Lions: "detroitlions",
  Packers: "GreenBayPackers",
  Panthers: "panthers",
  Patriots: "Patriots",
  Raiders: "raiders",
  Rams: "LosAngelesRams",
  Ravens: "ravens",
  Saints: "Saints",
  Seahawks: "Seahawks",
  Steelers: "steelers",
  Texans: "Texans",
  Titans: "Tennesseetitans",
  Vikings: "minnesotavikings",
};
export default teamSubreddits;
