const teams = [
  {
    primaryColor: "#AA0000",
    secondaryColor: "#B3995D",
    location: "San Francisco",
    name: "49ers",
    short: "SF",
  },
  {
    primaryColor: "#00338D",
    secondaryColor: "#C60C30",
    location: "Buffalo",
    name: "Bills",
    short: "BUF",
  },
  {
    primaryColor: "#0B162A",
    secondaryColor: "#C83803",
    location: "Chicago",
    name: "Bears",
    short: "CHI",
  },
  {
    primaryColor: "#FB4F14",
    secondaryColor: "#000000",
    location: "Cincinnati",
    name: "Bengals",
    short: "CIN",
  },
  {
    primaryColor: "#FB4F14",
    secondaryColor: "#002244",
    location: "Denver",
    name: "Broncos",
    short: "DEN",
  },
  {
    primaryColor: "#311D00",
    secondaryColor: "#FF3C00",
    location: "Cleveland",
    name: "Browns",
    short: "CLE",
  },
  {
    primaryColor: "#D50A0A",
    secondaryColor: "#FF7900",
    location: "Tampa Bay",
    name: "Buccaneers",
    short: "TB",
  },
  {
    primaryColor: "#97233F",
    secondaryColor: "#000000",
    location: "Arizona",
    name: "Cardinals",
    short: "ARI",
  },
  {
    primaryColor: "#002A5E",
    secondaryColor: "#FFC20E",
    location: "Los Angeles",
    name: "Chargers",
    short: "LAC",
  },
  {
    primaryColor: "#E31837",
    secondaryColor: "#FFB81C",
    location: "Kansas City",
    name: "Chiefs",
    short: "KC",
  },
  {
    primaryColor: "#002C5F",
    secondaryColor: "#A2AAAD",
    location: "Indianapolis",
    name: "Colts",
    short: "IND",
  },
  {
    primaryColor: "#003594",
    secondaryColor: "#041E42",
    location: "Dallas",
    name: "Cowboys",
    short: "DAL",
  },
  {
    primaryColor: "#008E97",
    secondaryColor: "#FC4C02",
    location: "Miami",
    name: "Dolphins",
    short: "MIA",
  },
  {
    primaryColor: "#004C54",
    secondaryColor: "#A5ACAF",
    location: "Philadelphia",
    name: "Eagles",
    short: "PHI",
  },
  {
    primaryColor: "#A71930",
    secondaryColor: "#000000",
    location: "Atlanta",
    name: "Falcons",
    short: "ATL",
  },
  {
    primaryColor: "#773141",
    secondaryColor: "#FFB612",
    location: "Washington",
    name: "Football Team",
    short: "WAS",
  },
  {
    primaryColor: "#0B2265",
    secondaryColor: "#A71930",
    location: "New York",
    name: "Giants",
    short: "NYG",
  },
  {
    primaryColor: "#125740",
    secondaryColor: "#000000",
    location: "New York",
    name: "Jets",
    short: "NYJ",
  },
  {
    primaryColor: "#101820",
    secondaryColor: "#D7A22A",
    location: "Jacksonville",
    name: "Jaguars",
    short: "JAC",
  },
  {
    primaryColor: "#0076B6",
    secondaryColor: "#B0B7BC",
    location: "Detroit",
    name: "Lions",
    short: "DET",
  },
  {
    primaryColor: "#203731",
    secondaryColor: "#FFB612",
    location: "Green Bay",
    name: "Packers",
    short: "GB",
  },
  {
    primaryColor: "#0085CA",
    secondaryColor: "#101820",
    location: "Carolina",
    name: "Panthers",
    short: "CAR",
  },
  {
    primaryColor: "#002244",
    secondaryColor: "#C60C30",
    location: "New England",
    name: "Patriots",
    short: "NE",
  },
  {
    primaryColor: "#D3BC8D",
    secondaryColor: "#101820",
    location: "New Orleans",
    name: "Saints",
    short: "NO",
  },
  {
    primaryColor: "#003594",
    secondaryColor: "#FFA300",
    location: "Los Angeles",
    name: "Rams",
    short: "LAR",
  },
  {
    primaryColor: "#000000",
    secondaryColor: "#A5ACAF",
    location: "Las Vegas",
    name: "Raiders",
    short: "LA",
  },
  {
    primaryColor: "#241773",
    secondaryColor: "#000000",
    location: "Baltimore",
    name: "Ravens",
    short: "BAL",
  },
  {
    primaryColor: "#002244",
    secondaryColor: "#69BE28",
    location: "Seattle",
    name: "Seahawks",
    short: "SEA",
  },
  {
    primaryColor: "#FFB612",
    secondaryColor: "#101820",
    location: "Pittsburgh",
    name: "Steelers",
    short: "PIT",
  },
  {
    primaryColor: "#03202F",
    secondaryColor: "#A71930",
    location: "Houston",
    name: "Texans",
    short: "HOU",
  },
  {
    primaryColor: "#0C2340",
    secondaryColor: "#4B92DB",
    location: "Tennessee",
    name: "Titans",
    short: "TEN",
  },
  {
    primaryColor: "#4F2683",
    secondaryColor: "#FFC62F",
    location: "Minnesota",
    name: "Vikings",
    short: "MIN",
  },
];

export default teams;
